"""
Built-in corpus of everyday conversational utterances.

These sentences are semantically unrelated to factual knowledge-base content
(Wikipedia passages, encyclopaedia articles, etc.) and are used to build the
null distribution of cosine similarity scores when no custom corpus is
provided by the user.

The corpus is derived from DailyDialog-style conversational English.
No external downloads are required at runtime.
"""

from __future__ import annotations

# ~250 short conversational utterances covering everyday topics.
_UTTERANCES: list[str] = [
    # Greetings and small talk
    "Hey, how have you been lately?",
    "It's been such a long week, I'm exhausted.",
    "What are you up to this weekend?",
    "I haven't seen you in ages!",
    "The weather has been really nice today.",
    "Did you catch the game last night?",
    "I really need a coffee right now.",
    "How's the family doing?",
    "Have you tried that new restaurant downtown?",
    "I can't believe it's already Friday.",
    "Are you heading out for lunch?",
    "It feels like summer came so fast this year.",
    "I'm so ready for the holidays.",
    "Traffic was terrible this morning.",
    "Did you hear about the new park opening nearby?",
    "My weekend was super relaxing, just stayed home.",
    "We should catch up soon, it's been forever.",
    "I've been binge-watching that new show everyone's talking about.",
    "The kids have been keeping me super busy.",
    "I finally got around to cleaning out my garage.",
    # Food and cooking
    "I made pasta from scratch last night, it turned out amazing.",
    "Have you ever tried making sushi at home?",
    "I'm on a diet but I keep craving pizza.",
    "The bakery on the corner makes the best croissants.",
    "I bought too many groceries again and now I don't know what to cook.",
    "Do you have a good recipe for banana bread?",
    "I've been trying to eat more vegetables lately.",
    "My favorite comfort food is grilled cheese with tomato soup.",
    "We had a barbecue last weekend, the burgers were incredible.",
    "I always burn my toast no matter what I do.",
    "Have you tried meal prepping? I started doing it and it saves so much time.",
    "The supermarket was out of eggs again.",
    "I just learned how to make homemade ice cream.",
    "She makes the most amazing apple pie every Thanksgiving.",
    "I can never resist stopping at the taco truck on Friday evenings.",
    # Work and daily routine
    "The morning meeting got cancelled, which was a relief.",
    "I have so many emails to catch up on.",
    "Working from home has really changed my routine.",
    "I finally finished that report I've been putting off.",
    "The printer in the office broke down again.",
    "I set three alarms but I still woke up late.",
    "My commute used to take an hour each way.",
    "I've been trying to take more breaks during the workday.",
    "We had a team lunch today and it was really fun.",
    "I keep forgetting to refill my water bottle at my desk.",
    "The office renovations are taking forever.",
    "I think I need a better chair; my back has been aching.",
    "I started a new planner system to get organized.",
    "We had a surprise birthday celebration for our manager.",
    "I finally got a standing desk and it's been a game changer.",
    # Shopping and errands
    "I spent way too much at the mall yesterday.",
    "The checkout line at the grocery store was insane.",
    "I've been online shopping too much lately.",
    "I need to return these shoes but I lost the receipt.",
    "The pharmacy was out of my medication.",
    "I found the most perfect dress on sale.",
    "I keep forgetting to pick up dry cleaning.",
    "The hardware store is having a big sale this week.",
    "I ordered something online two weeks ago and it still hasn't arrived.",
    "We finally bought that couch we've been saving up for.",
    "I impulse bought a kitchen gadget I'll probably never use.",
    "I'm trying to stop buying so many books when I haven't read the ones I own.",
    "The farmer's market on Saturdays is one of my favorite things.",
    "I need to get my car inspected this month.",
    "My gym membership renewal snuck up on me.",
    # Travel and leisure
    "I've been dreaming about a beach vacation.",
    "The last trip I took was to visit my cousins across the country.",
    "I'm thinking about taking a road trip this summer.",
    "Camping last weekend was so peaceful.",
    "I've never been on a cruise but I'd love to try it.",
    "My flight got delayed by three hours, it was so frustrating.",
    "I want to visit Japan someday, the food and culture look amazing.",
    "We went hiking on Saturday and my legs are still sore.",
    "I love exploring new neighborhoods in the city.",
    "The hotel we stayed at had the most comfortable beds.",
    "I always forget to pack something important when I travel.",
    "We're planning a family reunion trip next summer.",
    "I watched a documentary about Iceland and now I really want to go.",
    "The airport was packed with holiday travelers.",
    "I rented a bike to explore the city and it was so much fun.",
    # Hobbies and entertainment
    "I've been getting back into painting on weekends.",
    "I just finished an amazing novel, I couldn't put it down.",
    "I've been playing a lot of board games with friends lately.",
    "I started learning guitar and my fingers hurt.",
    "Gardening has become my favorite way to de-stress.",
    "I signed up for a pottery class and I love it.",
    "The concert last night was absolutely incredible.",
    "I've been doing puzzles every evening before bed.",
    "I went to an art exhibit downtown and it was really inspiring.",
    "I've been running every morning and I actually enjoy it now.",
    "I started a journal and it's been surprisingly helpful.",
    "We played charades at the party and laughed so hard.",
    "I've been collecting vinyl records for a few years.",
    "The new season of my favorite show just dropped.",
    "I tried rock climbing for the first time and it was terrifying.",
    # Health and wellness
    "I've been trying to get at least eight hours of sleep.",
    "My doctor told me to cut back on caffeine.",
    "I started meditating for ten minutes every morning.",
    "I finally joined a gym after months of saying I would.",
    "My allergies have been really bad this spring.",
    "I've been drinking more water and I feel so much better.",
    "The yoga class I tried was really challenging.",
    "I hurt my knee running and now I need to take it easy.",
    "I've been trying to cut down on screen time before bed.",
    "A good walk always clears my head when I'm stressed.",
    "I got a standing desk to help with my posture.",
    "I've been taking vitamins and I think they're actually helping.",
    "I need to schedule a dentist appointment I've been avoiding.",
    "I finally started physical therapy for my shoulder.",
    "Cooking more at home has made me feel so much healthier.",
    # Relationships and social life
    "My friend and I had the best catch-up over dinner last night.",
    "I'm going to a wedding next month and I have nothing to wear.",
    "My neighbor got a new puppy and it's adorable.",
    "We had a big family dinner and the whole house smelled amazing.",
    "I've been making more of an effort to call my parents.",
    "My best friend just had a baby, I'm so excited for them.",
    "We had a neighborhood block party last weekend.",
    "I've been trying to meet new people by joining a book club.",
    "My roommate and I finally sorted out the chore schedule.",
    "I bumped into an old classmate at the grocery store.",
    "We celebrated my parents' anniversary with a big surprise dinner.",
    "I've been hosting game nights on Fridays and it's been so fun.",
    "My cousin is visiting from out of town and I'm planning things to do.",
    "I had the most awkward reunion with someone I used to know.",
    "We all chipped in to get our friend an amazing birthday gift.",
    # Technology and gadgets
    "My phone battery dies so fast now, I think I need a new one.",
    "I finally updated my laptop and it runs so much faster.",
    "I've been trying to use fewer apps and it's harder than I thought.",
    "The Wi-Fi at home has been acting up all week.",
    "I got a new smartwatch and I'm obsessed with it.",
    "I set up a new photo printer and it was surprisingly easy.",
    "My keyboard started acting weird and I had to get a new one.",
    "I've been trying to organize all my files in the cloud.",
    "The smart home speaker sometimes mishears me in funny ways.",
    "I deleted social media apps off my phone for a week.",
    "My headphones broke right before a long flight, it was awful.",
    "I finally learned how to use the new project management app at work.",
    "I got a robot vacuum and now I wonder how I ever lived without it.",
    "My TV remote keeps disappearing into the couch cushions.",
    "I backed up my photos after losing some in a hard drive crash.",
    # Pets and nature
    "My cat knocked over my entire cup of tea this morning.",
    "We adopted a rescue dog and she's the sweetest thing.",
    "The birds at the feeder outside my window have been so active.",
    "My dog refuses to go outside when it rains.",
    "I found a stray kitten outside and now I'm debating keeping it.",
    "We saw a family of deer in the backyard this morning.",
    "My fish tank needs a good cleaning.",
    "The squirrels keep stealing from my bird feeder.",
    "I took my dog to the dog park and it was chaos.",
    "My neighbor's cat keeps visiting our yard and we've basically adopted it.",
    "I planted some herbs on my windowsill and they're thriving.",
    "We went birdwatching and spotted a really rare species.",
    "My hamster escaped its cage again last night.",
    "The fireflies in the backyard were magical last summer.",
    "We saw a beautiful sunrise on our morning walk.",
    # Money and finances
    "I've been trying to stick to a budget but it's tough.",
    "I finally paid off my credit card balance.",
    "I'm saving up for a new couch but it's taking forever.",
    "I found a coupon and saved twenty dollars at the store today.",
    "My car needs new tires and the timing couldn't be worse.",
    "I've been tracking my spending with an app and it's eye-opening.",
    "I signed up for a cash-back credit card to save on groceries.",
    "Rent went up again and I'm not sure what to do.",
    "I put some money into a savings account for emergencies.",
    "I finally cancelled all those subscriptions I wasn't using.",
    "I'm trying to stop eating out so much to save money.",
    "The utility bills have been really high this winter.",
    "I got a small bonus at work and I'm not sure how to spend it.",
    "I started a side project to earn a little extra income.",
    "I compared insurance plans and ended up switching providers.",
    # Miscellaneous
    "I can't decide what to watch; there are too many options.",
    "The laundry has been piling up and I keep ignoring it.",
    "I rearranged my living room and it feels so different.",
    "I've been waking up at six every morning even on weekends.",
    "The power went out for a few hours and it was weirdly peaceful.",
    "I found a five dollar bill in an old jacket pocket.",
    "I accidentally sent a message to the wrong person.",
    "The candle I bought smells incredible.",
    "I've been trying to declutter but every item has a memory.",
    "I'm learning how to fix things around the house instead of calling someone.",
    "My plants finally have new leaves after weeks of nothing.",
    "I stayed up too late and now I'm paying for it.",
    "I keep starting new projects and not finishing them.",
    "The library in my neighborhood is one of my favorite places.",
    "I bumped my elbow on the counter and it still hurts.",
    "I set a goal to read twelve books this year.",
    "I can never find matching socks in the morning.",
    "I reorganized my closet and donated three bags of clothes.",
    "I tried a new hiking trail and got a bit lost.",
    "My umbrella broke right when the rain started.",
]


def load_utterances() -> list[str]:
    """Return the built-in corpus of conversational utterances."""
    return list(_UTTERANCES)
